name: Doc Site
on:
  release:
    types: [published]
  push:
    branches: [ main ]
  workflow_dispatch:
jobs:
  deploy:
    runs-on: ubuntu-18.04
    steps:
      
      - name: Checkout
        uses: actions/checkout@master
      - name: setup node
        uses: actions/setup-node@v2
        with:
          node-version: 14
      - name: Run Npm Scripts
        run: |
          node -v
          yarn -v
          yarn
          yarn run build:docs
      - name: Deploy
        uses: peaceiris/actions-gh-pages@v2
        env:
          ACTIONS_DEPLOY_KEY: ${{ secrets.ACTIONS_DEPLOY_KEY }}
          PUBLISH_BRANCH: gh-pages
          PUBLISH_DIR: ./docs-dist
        with:
          emptyCommits: false
