# 名称
name: Release NPM
# 触发
on:
  push:
    tags: [ v* ]
  workflow_dispatch:

# 工作
jobs:
  deploy:
    runs-on: ubuntu-18.04
    steps:
      - name: Checkout
        uses: actions/checkout@master
      - name: setup node
        uses: actions/setup-node@v2
        with:
          node-version: 16
          registry-url: 'https://registry.npmjs.org'
      - name: Run Npm Scripts
        run: |
          node -v
          npm -v
          npm install
      - name: Change Version
        run: |
          echo ${{ github.ref }}
          node -e 'var pkg = require("./package.json"); pkg.version= "${{ github.ref }}"; require("fs").writeFileSync("./package.json", JSON.stringify(pkg, null, 2))'
      - name: Build
        run: |
          npm run build
      - name: NPM Publish
          cd lib
          npm publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN_CESHI1 }}