# 名称
name: Release NPM
# 触发
on:
  push:
    tags: [ v* ]
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-18.04
    steps:
      - name: Checkout
        uses: actions/checkout@master
      - name: setup node
        uses: actions/setup-node@v2
        with:
          node-version: 16
      - name: Run Npm Scripts
        run: |
          echo github.ref
          node -v
          npm -v
          npm install
          npm run build
      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.ref }}
          release_name: ${{ github.ref }}
          draft: false
          prerelease: false
